### ISSUE TITLE
Plugin Broke Again:

### ISSUE THREAD

**Issue by Crazys-Corner** [Dudewithoutname/DudeVoiceChat#2]
Hey, Recently the plugin keybind stopped working, and would send chat messages about changing voice modes whenever a user sprinted. Then it started completely bricking rocket. I was not able to run any commands until completely deleting the plugin from my server.

**Comment by Dudewithoutname** [comment]
Hi, thanks for the report, im currently working on version 2.0 so i don't plan fixing current version.
It's caused by unturned update that offsetted plugin hotkeys so try to change KeyId to 10 or higher also plugin does nothing with rocket so idk how it could break the rocket.

**Comment by Crazys-Corner** [comment]
Nor do I however once I removed it, commands started working again.

**Comment by Dudewithoutname** [comment]
Well you aren't the first one experiencing this kind of problem which is caused by the old harmony version.
Also i noticed that the version on github is older than the version from unturned store. Try using the version from unturned store
(don't forget to change 0harmony)
https://unturnedstore.com/products/131

(I apologize for my laziness)
